### ISSUE TITLE
UI Updates

### ISSUE THREAD

**Issue by shrnsubedi** [shrnsubedi/hamrobooks#1]
Update the UI for the page

**Todo:**

- [ ] Add cancel button to New Ad form
- [ ] Detail page UI update
- [ ] Detail page go back button
- [ ] Remove Front Page description with something else
